spring.application.name=back-end
jwt.secret=QWRtaW5TdXBlclNlY3JldEtleUZvckpXVDI1NkJpdHMxMjM0NTY=
jwt.expiration-ms=86400000

# Langchain4j Ollama properties
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen2.5:0.5b
langchain4j.ollama.chat-model.timeout=PT5M
